title: automations
icon: mdi:chemical-weapon
path: automations

cards:
  - type: entities
    show_header_toggle: false
    state_color: true
    entities:
      - automation.root_home
      - automation.root_not_home
      - automation.root_work
      - automation.n0ll_home
      - automation.n0ll_not_home
      - automation.home_away
      - automation.home_near
      - automation.just_home
      - type: divider
      - automation.change_pressure
      - automation.weather_alert
      - type: divider
      - automation.video_grabber
      - automation.tv_ctrl
      - automation.living_tv
      - type: divider
      - automation.open_ports
      - automation.auto_reboot_all
      - type: divider
      - automation.send_effect_hyperion
      - automation.updates_notify
      - automation.home_motion_detect
      - type: divider
      - automation.once_week_reboot
      - type: divider
      - automation.kitchen_light_1
      - type: divider
      - automation.auto_clean
      - type: divider
      - automation.clima_sync
      - automation.clima_max
      - type: divider
      - automation.ligths_auto_off
      - automation.zigbee2mqtt_start

  - type: entities
    show_header_toggle: false
    entities:
      - script.local_reboot
      - script.living_tv_reboot
      - script.owrt_reboot
      - script.village_reboot
      - script.zha_reboot
      - script.z2m_restart
