- platform: command_line
  command: '/home/hass/.homeassistant/cmds/tomato_smb_check'
  name: 'smb online'
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 300

- platform: command_line
  command: '/home/hass/.homeassistant/cmds/bravia_check'
  name: 'bravia'
  device_class: plug
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 300

- platform: template
  sensors:
    isp_conn:
      entity_id:
        - sensor.ping_isp
      device_class: connectivity
      delay_off:
        minutes: 16
      value_template: >-
        {%- if states.sensor.ping_isp.state == 'n/a' or
          states.sensor.ping_isp.state | float > 150 -%}
          False
        {%- else -%}
          True
        {%- endif %}
    batts_low:
      entity_id:
        - sensor.dht22_176e41_battery
        - sensor.bme280_171f93_battery
        - sensor.root_battery
        - climate.living
      device_class: battery
      value_template: >-
        {%- if states.sensor.dht22_176e41_battery.state and
                states.sensor.bme280_171f93_battery.state -%}
          {%- if
            states.sensor.dht22_176e41_battery.state|float <= states.input_number.slider_batt_level_v.state|float or
            states.sensor.bme280_171f93_battery.state|float <= states.input_number.slider_batt_level_v.state|float or
            states.sensor.root_battery.state|float <= states.input_number.slider_batt_level_p.state|float or
            is_state_attr('climate.living', 'low_battery', true) -%}
            True
          {%- else -%}
            False
          {%- endif %}
        {%- else -%}
          True
        {%- endif %}
    bedlight:
      entity_id:
        - sun.sun
        - device_tracker.n0ll
        - binary_sensor.sound_bar_active
        - timer.just_home
      device_class: light
      value_template: >-
        {%-if is_state("sun.sun", "below_horizon") and
             is_state("device_tracker.m4b30x", "home") -%}
          {%-if is_state("device_tracker.n0ll", "home") -%}
            False
          {%- else -%}
            {%- set  t =  (as_timestamp(now()) - as_timestamp(now().strftime('%Y-%m-%d 00:00')))-%}
            {%- set  ts =  states.input_datetime.bedl_time_start.attributes.timestamp -%}
            {%- set  te =  states.input_datetime.bedl_time_end.attributes.timestamp -%}
            {%-if (is_state("binary_sensor.sound_bar_active", "off") and
                  (ts < t or t < te) or
                  is_state("timer.just_home", "active"))
            -%}
              True
            {%- else -%}
              False
            {%- endif -%}
          {%- endif -%}
        {%- else -%}
          False
        {%- endif -%}
    sound_bar_active:
      entity_id:
        - media_player.htmt500501_b34d6a
        - binary_sensor.kodi_screen_saver
        - media_player.kodi
      device_class: sound
      delay_off:
        seconds: 60
      value_template: '{{
                          is_state("media_player.htmt500501_b34d6a", "playing") or
                          is_state("binary_sensor.kodi_screen_saver", "off") or
                          not is_state("media_player.kodi", "idle")
                          }}'
    bedmusic:
      entity_id:
        - sun.sun
        - device_tracker.n0ll
        - binary_sensor.sound_bar_active
      device_class: sound
      delay_on:
        seconds: 60
      delay_off:
        seconds: 60
      value_template: >-
        {%-if is_state("sun.sun", "below_horizon") and
             is_state("device_tracker.m4b30x", "home") -%}
          {%-if is_state("device_tracker.n0ll", "home") -%}
            False
          {%- else -%}
            {%- set  t =  (as_timestamp(now()) - as_timestamp(now().strftime('%Y-%m-%d 00:00')))-%}
            {%- set  ts =  states.input_datetime.bedm_time_start.attributes.timestamp -%}
            {%- set  te =  states.input_datetime.bedm_time_end.attributes.timestamp -%}
            {%-if (is_state("binary_sensor.sound_bar_active", "off") and
                  (ts < t or t < te))
            -%}
              True
            {%- else -%}
              False
            {%- endif -%}
          {%- endif -%}
        {%- else -%}
          False
        {%- endif -%}
    home_heating:
      entity_id:
        - device_tracker.n0ll
        - timer.just_home
        - timer.going_home
        - media_player.htmt500501_b34d6a
        - media_player.kodi
        - binary_sensor.kodi_screen_saver
      device_class: heat
      delay_off:
        minutes: 5
      value_template: >-
        {{
        is_state("device_tracker.n0ll", "home") or
        is_state("timer.just_home", "active") or
        is_state("timer.going_home", "active") or
        is_state("media_player.htmt500501_b34d6a", "playing") or
        is_state("binary_sensor.kodi_screen_saver", "off") or
        not is_state("media_player.kodi", "idle")
        }}

- platform: esp_wd
  name: x1
  host: !secret esp_host_x1
  scan_interval: 300

- platform: esp_wd
  name: test_1
  host: !secret test_host_1
  scan_interval: 300

- platform: esp_wd
  name: bedroom
  host: !secret bedroom
  scan_interval: 300

#uptimerobot.com angelgabriel.branson@oou.us
- platform: rest
  name: ext_port
  resource: https://api.uptimerobot.com/v2/getMonitors
  method: POST
  device_class: connectivity
  payload: api_key=m779688698-f03f19ccae5797b5123ea799&format=json&logs=0
  headers:
    Content-Type: application/x-www-form-urlencoded
    Cache-Control: no-cache
  value_template: '{{ value_json.monitors[0].status|int == 2 }}'
  scan_interval: 300

#- platform: bayesian
#  name: bedlight
#  prior: 0.2
#  probability_threshold: 0.85
#  observations:
#    - entity_id: sensor.sun
#      prob_given_true: 0.8
#      platform: state
#      to_state: below_horizon
#    - entity_id: device_tracker.m4b30x
#      prob_given_true: 0.6
#      platform: state
#      to_state: home
#    - entity_id: device_tracker.n0ll
#      prob_given_true: 0.7
#      platform: state
#      to_state: not_home
#    - entity_id: media_player.kodi
#      prob_given_true: 0.9
#      platform: state
#      to_state: idle
