- platform: tomato
  consider_home: 120
  interval_seconds: 60
  host: !secret tomato_host
  port: !secret tomato_port
  username: !secret tomato_user
  password: !secret tomato_pass
  http_id: !secret tomato_httpid
  new_device_defaults:
    track_new_devices: false
    hide_if_away: false

- platform: gpslogger

- platform: google_maps
  username: !secret g_user
  password: !secret g_pass
  interval_seconds: 60
