- platform: tomato
  consider_home: 120
  interval_seconds: 60
  track_new_devices: no
  host: !secret tomato_host
  username: !secret tomato_user
  password: !secret tomato_pass
  http_id: !secret tomato_httpid

- platform: gpslogger
