- platform: mqtt_template
  name: 'bed led'
  effect_list:
    - cycle
    - none
  command_topic: "/bedroom_led/cmd"
  state_topic: "/bedroom_led/status/led"
  command_on_template: >-
    {{"rgb_json,{'state':'on'"}}
    {%- if brightness is defined -%}
    ,'brightness':{{brightness}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
      ,'r':{{red}},'g':{{green}},'b':{{blue}}
    {%- endif -%}
    {%- if transition is defined -%}
      ,'transition':{{transition |int * 1000}}
    {%- else -%}
      ,'transition':{{3000}}
    {%- endif -%}
    {%- if effect is defined -%}
      ,'eff':'{{effect}}','eff_time':{{states.input_number.bed_cycle_duration.state|int}}
    {%- endif -%}
    {{"}"}}

  command_off_template: >-
    {{"rgb_json,{'state':'off'"}}
    {%- if transition is defined -%}
    ,'transition':{{transition |int * 1000}}
    {%- endif -%}
    {{"}"}}

  state_template: '{{ value_json.state }}'
  brightness_template: '{{ value_json.brightness }}'
  red_template: '{{ value_json.r }}'
  green_template: '{{ value_json.g }}'
  blue_template: '{{ value_json.b }}'
  effect_template: '{{ value_json.eff }}'
  availability_topic: "/bedroom_led/status"
  payload_available: "Connected"
  payload_not_available: "Connection Lost"
