automation:
  - alias: follow_on
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.light_follow
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.light_auto_follow

  - alias: follow_off_cancel
    trigger:
      - platform: state
        entity_id: input_boolean.light_auto_follow
        to: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.light_follow

  - alias: follow_off
    trigger:
      - platform: state
        entity_id: input_boolean.light_auto_follow
        to: 'off'
    action:
      - service: timer.start
        entity_id: timer.light_follow
        data_template:
          duration: '00:{{states.input_number.light_follow_off_time.state|int}}:00'

group:
  auto_follow:
    view: false
    control: hidden
    name: follow
    entities:
    - input_boolean.light_auto_follow
    - input_number.light_follow_off_time
    - timer.light_follow
    - automation.follow_on
    - automation.follow_off

input_boolean:
  light_auto_follow:
    name: follow
    icon: mdi:track-light
    initial: on

input_number:
  light_follow_off_time:
    name: 'time'
    unit_of_measurement: 'min'
    min: 1
    max: 15
    step: 1
    icon: mdi:timer-sand

timer:
  light_follow:
    name: 'follow off time'
    icon: mdi:timer
    duration: '00:00:30'
