- platform: kodi
  host: !secret kodi_host
  port: !secret kodi_port
  username: !secret kodi_user
  password: !secret kodi_pass

- platform: cast
  host: !secret cast_bedroom
- platform: cast
  host: !secret cast_sound_bar
