- platform: kodi
  name: kodi
  host: !secret kodi_host
  port: !secret kodi_port
  username: !secret kodi_user
  password: !secret kodi_pass

- platform: smtp
  name: mailbg
  server: smtp.mail.bg
  port: 465
  timeout: 10
  sender: !secret smtp_user
  encryption: tls
  username: !secret smtp_user
  password: !secret smtp_pass
  recipient:
    - !secret smtp_recp
  sender_name: Hass
