- platform: kodi
  name: kodi
  host: !secret kodi_host
  port: !secret kodi_port
  username: !secret kodi_user
  password: !secret kodi_pass

- platform: smtp
  name: gmail
  server: smtp.gmail.com
  port: 587
  timeout: 15
  sender: hass@gmail.com
  encryption: starttls
  username: !secret g_user
  password: !secret g_pass
  recipient:
    - !secret smtp_recp
