#- platform: yr
  #monitored_conditions:
    #- symbol

- platform: darksky
  api_key: !secret darksky_key
  update_interval:
    minutes: 5
  units:
    si
  monitored_conditions:
    #- nearest_storm_distance
    #- icon
    - temperature
    - wind_speed
    - humidity
    - pressure
    - precip_intensity

- platform: wunderground
  api_key: !secret wnderground_key
  pws_id: ISOFIA368
  monitored_conditions:
    - alerts
    #- temp_c
    #- pressure_mb
    #- relative_humidity
    #- wind_kph
    - weather
    #- weather_3h
    #- weather_6h
    #- weather_12h
    #- weather_24h
    #- precip_today_metric

- platform: template
  sensors:
    root_battery:
      unit_of_measurement: '%'
      icon_template: 'mdi:gauge'
      value_template: >-
          {%- if states.device_tracker.m4b30x.attributes.battery %}
             {{ states.device_tracker.m4b30x.attributes.battery }}
          {% else %}
              {{ states.sensor.root_battery.state }}
          {%- endif %}
    sea_level_pressure:
      friendly_name: 'sea pressure'
      unit_of_measurement: 'hPa'
      icon_template: 'mdi:gauge'
      value_template: >-
          {%- if states('sensor.pressure_history_mean') != 'unknown' and
                  states('sensor.dht22_176e41_temperature') != 'unknown' %}
              {% set p1 = states.sensor.pressure_history_mean.state | float %}
              {% set t = states.sensor.dht22_176e41_temperature.state | float %}
              {% set h = 603 | float %}
              {{ (p1 *  ( (1 - (0.0065 * h) / (t + (0.0065 * h) + 273.15)) **  -5.257)) | round(2) }}
          {% else %}
              {{ states.sensor.sea_level_pressure.state }}
          {%- endif %}
    change_pressure:
      friendly_name: 'change'
      unit_of_measurement: 'hPa/h'
      value_template: >-
        {{states.sensor.pressure_history_mean.attributes.change|round(2)}}
      icon_template: >-
        {%if states.sensor.pressure_history_mean.attributes.change|float > 0.33 %}
          {{'mdi:trending-up'}}
        {% elif states.sensor.pressure_history_mean.attributes.change|float < -0.33 %}
          {{'mdi:trending-down'}}
        {% else %}
          {{'mdi:trending-neutral'}}
        {% endif %}
    valve_living:
      unit_of_measurement: '%'
      icon_template: 'mdi:percent'
      value_template: >-
        {%- if states('climate.living') != 'unavailable' -%}
          {{ states.climate.living.attributes.valve|int }}
        {% else -%}
          {{ states.sensor.valve_living.state }}
        {%- endif -%}
    temperature_living:
      unit_of_measurement: '°C'
      icon_template: 'mdi:temperature-celsius'
      value_template: >-
        {%- if states('climate.living') != 'unavailable' -%}
          {{ states.climate.living.attributes.temperature|float }}
        {% else -%}
          {{ states.sensor.temperature_target_living.state }}
        {%- endif -%}

- platform: command_line
  name: CPU Temp
  command: "/home/hass/.homeassistant/cmds/cpu_temp"
  unit_of_measurement: "°C"
  scan_interval: 300

- platform: command_line
  name: Disk Free
  command: "/home/hass/.homeassistant/cmds/disk_free"
  unit_of_measurement: "MB"
  scan_interval: 300

- platform: command_line
  name: Cpu Usage
  command: "/home/hass/.homeassistant/cmds/cpu_usage"
  unit_of_measurement: "%"
  scan_interval: 300

- platform: command_line
  name: Mem Free
  command: "/home/hass/.homeassistant/cmds/mem_free"
  unit_of_measurement: "MB"
  scan_interval: 300

- platform: command_line
  name: ping isp
  command: "/home/hass/.homeassistant/cmds/test_isp"
  unit_of_measurement: "ms"
  scan_interval: 300

- platform: command_line
  name: tomato disk free
  command: "/home/hass/.homeassistant/cmds/tomato_disk_free"
  unit_of_measurement: "MB"
  scan_interval: 600

- platform: statistics
  name: pressure history
  entity_id: sensor.bme280_171f93_pressure
  sampling_size: 6

- platform: mqtt
  name: "hum b"
  state_topic: "/bedroom_led/env/humidity"
  unit_of_measurement: "%"
  expire_after: 660

- platform: mqtt
  name: "temp b"
  state_topic: "/bedroom_led/env/temperature"
  unit_of_measurement: "°C"
  expire_after: 660

#- platform: snmp
  #name: 'router load 1m'
  #host: !secret snmp_router
  #baseoid: 1.3.6.1.4.1.2021.10.1.5.1
  #version: 2c
  #community: !secret snmp_pass
  #accept_errors: true
  #unit_of_measurement: 'minutes'
  #value_template: '{{(value | int)}}'
