- platform: command_line
  switches:
    hyperion_enable:
      command_on: "/home/hass/.homeassistant/cmds/hyperion_on"
      command_off: "/home/hass/.homeassistant/cmds/hyperion_off"

- platform: command_line
  switches:
    tv_picture_off:
      command_on: "/home/hass/.homeassistant/cmds/kodi_picoff"
      command_off: "/home/hass/.homeassistant/cmds/kodi_picoff"

- platform: command_line
  switches:
    tv_cec:
      command_on: "/home/hass/.homeassistant/cmds/cec_on"
      command_off: "/home/hass/.homeassistant/cmds/cec_off"
