#!/bin/bash

_HA=${_HA:=hass}

up () {
    rsync --inplace -ravz --info=progress2 -e ssh ./ ${_HA}:~/homeassistant/ \
    --exclude=zigbee.db \
    --exclude='.storage/*' \
    --exclude='neighbours*' \
    --exclude-from=exclude_list \
    --delete
}

down () {
    rsync --inplace -ravz --info=progress2 -e ssh ${_HA}:~/homeassistant/ ./ \
    --exclude-from=exclude_list \
    --delete \
    --force
}

case $1 in
  pull)
    down
    ;;

  push)
    up
    ;;

  *)
    echo "unknown"
    ;;
esac
