resources:
  - url: /customcards/github/custom-cards/upcoming-media-card.js?track=true
    type: js
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/nervetattoo/simple-thermostat.js?track=true
    type: module
  - url: /local/custom-weather-card-chart.js?track=true
    type: module
  - url: /customcards/github/custom-cards/flex-table-card.js?track=true
    type: js

title: home
views:
  - !include lovelace/home.yaml
  - !include lovelace/bed.yaml
  - !include lovelace/status.yaml
  - !include lovelace/settings.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/hyperion.yaml
  - !include lovelace/light.yaml
  - !include lovelace/tracker.yaml
  - !include lovelace/other.yaml
  #- title: xxx
   #path: xxx
   #icon: mdi:keyboard-variant
   #cards:
     #- type: iframe
       #url: 'https://embed.windy.com/embed2.html?lat=42.614&lon=25.115&zoom=6&level=surface&overlay=temp&calendar=24&pressure=true&type=map&location=coordinates&detail=&detailLat=42.614&detailLon=25.115&metricWind=km%2Fh&metricTemp=%C2%B0C'
