title: home
views:
  - !include lovelace/home.yaml
  - !include lovelace/climate.yaml
  - !include lovelace/light.yaml
  - !include lovelace/bed.yaml
  - !include lovelace/bath.yaml
  - !include lovelace/shutters.yaml
  - !include lovelace/status.yaml
  - !include lovelace/settings.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/tracker.yaml
  - !include lovelace/other.yaml
  - !include lovelace/vacuum.yaml
  - !include lovelace/homeconnect.yaml
  - !include lovelace/lock.yaml
  - !include lovelace/city.yaml
  - !include lovelace/village.yaml
  - !include lovelace/energy.yaml
  - !include lovelace/lora.yaml
  # - !include lovelace/helium.yaml
  # - title: xxx
  #   path: xxx
  #   icon: mdi:keyboard-variant
  #   cards:
  #     - type: iframe
  #       url: 'https://embed.windy.com/embed2.html?lat=42.614&lon=25.115&zoom=6&level=surface&overlay=temp&calendar=24&pressure=true&type=map&location=coordinates&detail=&detailLat=42.614&detailLon=25.115&metricWind=km%2Fh&metricTemp=%C2%B0C'
