automation:
  - alias: event_android_alarm
    trigger:
      - platform: event
        event_type: android_alarm
    action:
      - service: timer.start
        entity_id: timer.post_android_alarm
        data_template:
          duration: '00:{{states.input_number.post_android_alarm.state|int}}:00'
      - service: logbook.log
        data_template:
          name: 'ha_alarm'
          message: 'timer arm {{states.input_number.post_android_alarm.state}} min'

  - alias: post_android_alarm
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.post_android_alarm
    condition:
      - condition: and
        conditions:
          - condition: template
            value_template: >-
              {{
                  not is_state('media_player.bedroom_speaker', 'playing')
                }}
    action:
      - service: script.android_post_alarm

script:
  android_post_alarm_swich:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.select_radio_bed
          option: Nova Bg

  android_post_alarm:
    sequence:
      - condition: state
        entity_id: device_tracker.root
        state: 'home'
      - service: logbook.log
        data:
          name: 'ha_alarm'
          message: 'run'
      - service_template: >-
          {%- if 'Nova Bg' == states("input_select.select_radio_bed") -%}
            script.bed_music_on
          {%- else -%}
            script.android_post_alarm_swich
          {%- endif -%}
      - wait_template: "{{ is_state('media_player.bedroom_speaker', 'playing')}}"
        timeout: '00:00:15'
        continue_on_timeout: 'true'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom_speaker
          volume_level: 0.16

input_number:
  post_android_alarm:
    name: 'delay'
    unit_of_measurement: 'min'
    min: 1
    max: 9
    step: 1
    icon: mdi:alarm-multiple

timer:
  post_android_alarm:
    name: 'time delay'
    icon: mdi:timer-outline
    duration: '00:05:00'
