homeassistant:
  customize:
    light.bed:
      icon: mdi:track-light
    automation.bed_light:
      icon: mdi:lightbulb-auto
      friendly_name: bed
    automation.other_bed_light:
      icon: mdi:lightbulb-auto
      friendly_name: bed

automation:
  - id: bed_light
    alias: bed_light
    initial_state: false
    triggers:
      - trigger: state
        entity_id: binary_sensor.bed_motion
        to: 'on'
        id: light_on
      - trigger: state
        entity_id: binary_sensor.bed_occupancy
        to: 'off'
        for:
          seconds: 60
        id: light_off
      - trigger: state
        entity_id: binary_sensor.living_motion
        to: 'on'
        id: light_off
      - trigger: state
        entity_id: binary_sensor.office_motion
        to: 'on'
        id: light_off
      - trigger: event
        event_type: lights_check
        event_data:
          light: turn_off
        id: light_off

    mode: restart
    actions:
      - variables:
          cfg: >-
            {% from 'tools.jinja' import light_cfg %}
            {{ light_cfg(is_state('binary_sensor.night_mode', 'off')) | from_json }}
      - choose:
        - conditions:
          - condition: trigger
            id:
              - light_on
          - condition: state
            entity_id: light.bed
            state: 'off'
          - condition: state
            entity_id: binary_sensor.day
            state: 'off'
          sequence:
            - action: script.lights_on
              data:
                ctrl_light: light.bed
                ctrl_all: >-
                  {{ is_state('binary_sensor.night_mode', 'off') }}
                brightness_pct: >-
                  {{ cfg.brightness }}
                transition: >-
                  {{ cfg.transition }}
                color_temp: >-
                  {{ cfg.temp }}

        - conditions:
          - condition: trigger
            id:
              - light_off
          - condition: state
            entity_id: light.bed
            state: 'on'
          - condition: state
            entity_id: binary_sensor.bed_occupancy
            state: 'off'
          sequence:
            - action: script.lights_off
              data:
                ctrl_light: light.bed
                transition: >-
                  {{ cfg.transition }}

  - id: other_bed_light
    alias: other_bed_light
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.bed_motion
          - binary_sensor.night_mode_ctrl
        to: 'on'
        id: light_on
      - trigger: state
        entity_id: binary_sensor.bed_occupancy
        to: 'off'
        for:
          seconds: 120
        id: light_off
      - trigger: state
        entity_id: binary_sensor.night_mode_ctrl
        to: 'off'
        id: light_ctrl_off
      - trigger: event
        event_type: lights_check
        event_data:
          light: turn_off
        id: light_ctrl_off

    mode: restart
    actions:
      - choose:
        - conditions:
          - condition: trigger
            id:
              - light_on
          - condition: state
            entity_id: binary_sensor.bed_occupancy
            state: 'on'
          - condition: state
            entity_id: binary_sensor.night_mode_ctrl
            state: 'on'
          - condition: state
            entity_id: light.shutter_bed
            state: 'off'
          sequence:
            - action: light.turn_on
              target:
                entity_id:
                  - light.shutter_bed

        - conditions:
          - condition: trigger
            id:
              - light_off
          - condition: state
            entity_id: binary_sensor.bed_occupancy
            state: 'off'
          - condition: state
            entity_id: light.shutter_bed
            state: 'on'
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.shutter_bed

        - conditions:
          - condition: trigger
            id:
              - light_ctrl_off
          - condition: state
            entity_id: light.shutter_bed
            state: 'on'
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.shutter_bed

      - choose:
        - conditions:
          - condition: trigger
            id:
              - light_on
          - condition: state
            entity_id: binary_sensor.bed_occupancy
            state: 'on'
          - condition: state
            entity_id: input_boolean.in_bed_dummy_switch
            state: 'off'
          - condition: state
            entity_id: light.bed_wardrobe
            state: 'off'
          sequence:
            - action: light.turn_on
              target:
                entity_id:
                  - light.bed_wardrobe

        - conditions:
          - condition: trigger
            id:
              - light_off
          - condition: state
            entity_id: binary_sensor.bed_occupancy
            state: 'off'
          - condition: state
            entity_id: light.bed_wardrobe
            state: 'on'
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.bed_wardrobe

        - conditions:
          - condition: trigger
            id:
              - light_ctrl_off
          - condition: state
            entity_id: light.bed_wardrobe
            state: 'on'
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.bed_wardrobe

light:
  - platform: group
    name: bed
    entities:
      - light.bed_1
      - light.bed_2
      - light.bed_3
      - light.bed_4
      - light.bed_5
      - light.bed_6
      - light.bed_7
      - light.bed_8
