homeassistant:
  customize:
    alert.cpu_overheat:
      icon: mdi:thermometer-lines
    sensor.cpu_overheat:
      friendly_name: Cpu

alert:
  cpu_overheat:
    name: cpu
    title: cpu {{states('sensor.cpu_temp')}}{{state_attr('sensor.cpu_temp', 'unit_of_measurement')}}
    message: overheat
    done_message: cool
    entity_id: binary_sensor.cpu_overheat
    state: 'on'
    repeat:
      - 5
      - 5
      - 10
    skip_first: true
    can_acknowledge: true
    notifiers:
      - kodi
      - gmail

template:
  - binary_sensor:
    - name: cpu_overheat
      device_class: heat
      delay_on:
        seconds: 10
      delay_off:
        seconds: 5
      state: >-
        {{states('sensor.cpu_temp') >= states('input_number.cpu_temp_level')}}

input_number:
  cpu_temp_level:
    name: 'cpu'
    unit_of_measurement: '°C'
    min: 45
    max: 70
    step: 1
    icon: mdi:thermometer-lines
