automation:
  - alias: hall_light_trigger
    trigger:
      - platform: state
        entity_id: binary_sensor.lumi_lumi_sensor_motion_c56e2702_ias_zone
        to: 'on'
    action:
      - service: script.hall_auto_on_light

  - alias: hall_light_other_clear
    trigger:
      - platform: state
        entity_id: binary_sensor.lumi_lumi_sensor_motion_c56e2702_occupancy
        to: 'on'
        for:
          seconds: 3
    action:
      - service: script.living_clear_timer
      - service: script.bed_clear_timer

  - alias: hall_light_on
    trigger:
      - platform: state
        entity_id: timer.hall_light_timer
        to: 'active'
        from: 'idle'
    action:
      # transition not work if current and
      # target brightness are diffrent
      - service: light.turn_on
        data:
          entity_id: light.hall_light
          brightness_pct: 1
          kelvin: 2700
      - service: light.turn_on
        data:
          entity_id: light.hall_light
          transition: 5
          brightness_pct: 85

  - alias: hall_light_off
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.hall_light_timer
    action:
      - service: light.turn_off
        data:
          entity_id: light.hall_light

input_number:
  hall_light_time:
    name: 'hall'
    unit_of_measurement: 'sec'
    min: 5
    max: 180
    step: 5
    icon: mdi:camera-timer

script:
  hall_auto_on_light:
    sequence:
      - condition: and
        conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: device_tracker.root
              state: 'home'
            - condition: state
              entity_id: binary_sensor.day
              state: 'off'
      - service: logbook.log
        data:
          name: 'Hall light'
          message: 'On'
      - service: timer.start
        entity_id: timer.hall_light_timer
        data_template:
          duration: "{{ states('input_number.hall_light_time') | int }}"

  hall_clear_timer:
    sequence:
      - condition: and
        conditions:
          - condition: state
            entity_id: timer.hall_light_timer
            state: 'active'
      - service: timer.finish
        entity_id: timer.hall_light_timer

light:
  - platform: group
    name: 'hall light'
    entities:
      - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_bd3600fe_level_light_color_on_off
      - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_6aa35efe_level_light_color_on_off
      - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_d7e032fe_level_light_color_on_off

timer:
  hall_light_timer:
    name: 'light time'
    icon: mdi:timer
    duration: '00:00:30'
