homeassistant:
  customize:
    binary_sensor.water_wash:
      friendly_name: washing
    binary_sensor.wash_fan:
      friendly_name: fan
    alert.water_on:
      icon: mdi:liquid-spot
    automation.reload_homeconect:
      friendly_name: reload
      icon: mdi:wifi-refresh

alert:
  water_on:
    name: water
    entity_id: binary_sensor.warn_valve_1
    state: 'on'
    repeat:
      - 30
      - 60
    can_acknowledge: true
    skip_first: true
    title: water
    message: valve is on
    done_message: valve is off
    notifiers:
      - gmail

template:
  - binary_sensor:
    - name: water_wash
      delay_off:
        seconds: 30
      state: >-
        {{
          (
            is_state('input_boolean.water_manual_ctrl', 'on') or
              (
                states('sensor.bosch_washer_operation_state') in
                  [
                      'Run',
                    ] and
                  is_state('binary_sensor.bosch_washer_door', 'off') and
                  is_state('device_tracker.washer', 'home')
                ) or
              (
                states('sensor.bosch_dishwasher_operation_state') in
                  [
                      'Run',
                    ] and
                  is_state('binary_sensor.bosch_dishwasher_door', 'off') and
                  is_state('device_tracker.dishwasher', 'home')
                )
            )
          }}
      icon: mdi:valve

    - name: wash_fan
      delay_off:
        seconds: 30
      state: >-
        {{
            (
              states('sensor.bosch_dryer_operation_state') in
                [
                    'Run',
                  ] or
                is_state('binary_sensor.bosch_dryer_door', 'on')
                and is_state('device_tracker.dryer', 'home')
              ) or
            (
              is_state('binary_sensor.bosch_washer_door', 'on') and
                states('sensor.bosch_washer_operation_state') in
                  [
                      'Finished',
                      'Ready'
                    ] and
                is_state('device_tracker.washer', 'home')
              )
          }}
      icon: mdi:fan

    - name: warn_valve_1
      state: >-
        {{
            is_state('device_tracker.root', 'not_home') and
              is_state('switch.water_valve', 'on')
          }}
      device_class: problem
      icon: mdi:liquid-spot

automation:
  - alias: reload_homeconect
    id: reload_homeconect
    triggers:
      - trigger: state
        entity_id:
          - device_tracker.washer
        to: home
        for:
          seconds: 15
        variables:
          to_reload: f39429634a6003bd183b31931d0b0c45

      - trigger: state
        entity_id:
          - device_tracker.dryer
        to: home
        for:
          seconds: 15
        variables:
          to_reload: 77de543d8924bda7bc2df77843728363

      - trigger: state
        entity_id:
          - device_tracker.dishwasher
        to: home
        for:
          seconds: 15
        variables:
          to_reload: 1b845c3081a50d17627582404e2b9089

    actions:
      - action: homeassistant.reload_config_entry
        target:
          device_id: >-
            {{ to_reload }}
