automation:
  - alias: n0ll_home
    trigger:
      - platform: state
        entity_id: device_tracker.n0ll
        from: not_home
        to: home
    action:
      - service: script.n0ll_home

  - alias: home_near
    trigger:
      - platform: numeric_state
        entity_id: proximity.home
        below: 30
    condition:
      - condition: template
        value_template: >-
          {{
            is_state_attr('proximity.home', 'dir_of_travel', 'towards') or
            is_state_attr('proximity.home', 'dir_of_travel', 'arrived')
          }}
    action:
      - service: script.home_near

  - alias: root_home
    initial_state: off
    trigger:
      - platform: zone
        entity_id: device_tracker.root
        zone: zone.home
        event: enter
    action:
      - service: automation.turn_on
        entity_id: automation.just_home

  - alias: just_home
    trigger:
      - platform: state
        entity_id: binary_sensor.living_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.hall_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bed_motion
        to: 'on'
    action:
      - service: script.just_home
      - service: automation.turn_off
        entity_id:
          - automation.just_home
          - automation.home_motion_detect

  - alias: minix_home
    trigger:
      - platform: state
        entity_id: device_tracker.minix
        to: home
        for:
          minutes: 3
    action:
      - service: script.minix_home

script:
  just_home:
    sequence:
      - service: script.radio_on
      - service: automation.turn_on
        entity_id:
          - automation.motion_light_extend
          - automation.just_home_auto
      - service: timer.start
        entity_id: timer.just_home_light
        data_template:
          duration: '{{states.input_number.just_home_light_timer.state|int * 60}}'
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_motion

  n0ll_home:
    sequence:
      - service_template: >-
          {%- if is_state("binary_sensor.kodi_screen_saver", "off")  -%}
            shell_command.kodi_screensaver
          {%- else -%}
            script.radio_on
          {%- endif -%}
      - service: automation.trigger
        entity_id: automation.send_rgb_hyperion
      - condition: state
        entity_id: media_player.htmt500501_b34d6a
        state: 'playing'
      - service: timer.pause
        entity_id: timer.sound_bar

  home_near_turnon:
    sequence:
      - service: switch.turn_on
        entity_id:
          - switch.av_switch
          - switch.bed_switch

  home_near:
    sequence:
      - service: notify.gmail
        data:
          message: home near trigger
          title: 'hass'
      - service: automation.turn_off
        entity_id: automation.home_near
      - service: automation.turn_on
        entity_id:
          - automation.home_away
          - automation.minix_home
      - service: script.home_near_heating
      - service: script.home_near_turnon

  minix_home:
    sequence:
      - service: notify.gmail
        data:
          message: minix near trigger
          title: 'hass'
      - service: automation.turn_off
        entity_id: automation.minix_home
      - delay: '00:00:30'
      - service: homeassistant.restart
