homeassistant:
  customize:
    automation.sonarr_radarr_notify:
      icon: mdi:bullhorn
    automation.sonarr_radarr_db:
      icon: mdi:download-network
    automation.update_video_db:
      icon: mdi:database-search
    automation.kodi_clear_tv_db:
      icon: mdi:delete-variant

automation:
  - alias: kodi clear tv db
    trigger:
      - platform: event
        event_type: tv_cec_control_done
        event_data:
          cec: 'off'
    condition:
      - condition: state
        entity_id: media_player.kodi
        state: idle
    action:
      - service: kodi.call_method
        data:
          entity_id: media_player.kodi
          method: Addons.SetAddonEnabled
          addonid: pvr.hts
          enabled: false
      - delay: '00:00:05'
      - service: shell_command.tv_cleardb
      - delay: '00:00:01'
      - service: kodi.call_method
        data:
          entity_id: media_player.kodi
          method: Addons.SetAddonEnabled
          addonid: pvr.hts
          enabled: true
      - delay: '00:00:05'
      - service: kodi.call_method
        data:
          entity_id: media_player.kodi
          method: VideoLibrary.Clean

  - alias: update_video_db
    trigger:
      - platform: event
        event_type: tv_cec_control_done
        event_data:
          cec: 'on'
      - platform: state
        entity_id: media_player.kodi
        to: 'idle'
        for:
          seconds: 10
      - platform: state
        entity_id: media_player.kodi
        to: 'paused'
        for:
          seconds: 10
    action:
      - service: automation.turn_off
        entity_id: automation.update_video_db
      - service: script.update_video_db
      - service: logbook.log
        data_template:
          name: 'videodb'
          message: 'trigger update'

  - alias: sonarr_radarr_notify
    trigger:
      - platform: event
        event_type: update_video_db
    action:
      - service: script.all_notify
        data_template:
          tit: '{{trigger.event.data.name}}'
          msg: '{{trigger.event.data.eventtype}}'
      - service: logbook.log
        data_template:
          name: 'downloads'
          message: '{{trigger.event.data}}'

  - alias: sonarr_radarr_db
    trigger:
      - platform: event
        event_type: update_video_db
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{
              trigger.event.data.eventtype in ['Download', 'Rename']
              }}
    action:
      - service: automation.turn_on
        entity_id: automation.update_video_db

  - alias: bazarr_subs
    trigger:
      - platform: event
        event_type: bazarr_subs
    action:
      - service: script.all_notify
        data_template:
          tit: 'bazarr'
          msg: '{{trigger.event.data.message}}'
      - service: logbook.log
        data_template:
          name: 'bazarr'
          message: '{{trigger.event.data}}'

script:
  update_video_db:
    sequence:
      - service: kodi.call_method
        data:
          entity_id: media_player.kodi
          method: VideoLibrary.Scan

shell_command:
  tv_cleardb: '/config/cmds/tv_cleardb'

