homeassistant:
  customize:
    automation.root_not_home:
      friendly_name: away
      icon: mdi:home-outline
    automation.n0ll_not_home:
      friendly_name: pc away
      icon: mdi:monitor-speaker-off
    automation.home_away:
      friendly_name: city away
      icon: mdi:home-city-outline

automation:
  - alias: n0ll_not_home
    id: n0ll_not_home
    triggers:
      - trigger: state
        entity_id: device_tracker.n0ll
        to: not_home
        for:
          seconds: 90
    actions:
       - action: script.sound_bar_go_sleep

  - alias: root_not_home
    id: root_not_home
    initial_state: off
    triggers:
      - trigger: zone
        entity_id: device_tracker.root
        zone: zone.home
        event: leave
    actions:
      - action: script.turn_on
        data:
          entity_id:
            - script.light_extend_clear
      - action: media_player.turn_off
        entity_id:
          - media_player.ht_mt500_501_b34d6a
          - media_player.bedroom_speaker
      - action: script.kodi_turn_off
      # - action: automation.turn_on
      #   entity_id: automation.home_motion_detect
      - action: automation.turn_off
        entity_id:
          - automation.just_home
          # - automation.motion_light_extend

  - alias: home_away
    id: home_away
    triggers:
      - trigger: numeric_state
        entity_id: sensor.home_root_distance
        above: 15
        id: away
      - trigger: state
        entity_id: input_boolean.away_skip
        for:
          seconds: 3
        id: away_skip

    mode: restart
    actions:
      - choose:
        - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id:
                  - away
              - condition: and
                conditions:
                  - condition: trigger
                    id:
                      - away_skip
                  - condition: state
                    entity_id: input_boolean.away_skip
                    state: 'off'
                  - condition: numeric_state
                    entity_id: sensor.home_root_distance
                    above: 15
          sequence:
            - if:
              - condition: state
                entity_id: input_boolean.away_skip
                state: 'off'
              then:
                - action: notify.gmail
                  data:
                    message: home away trigger
                    title: 'hass'
                - action: script.turn_on
                  target:
                    entity_id:
                      - script.doors_full_lock
                - action: switch.turn_off
                  entity_id:
                    - switch.living_tv
                    - switch.bed_switch_1
                - action: automation.turn_on
                  entity_id: automation.home_near
                - action: automation.turn_off
                  entity_id: automation.home_away
              else:
                - action: script.all_notify
                  data:
                    tit: home_away
                    msg: skip

      - choose:
        - conditions:
          - condition: trigger
            id:
              - away_skip
          sequence:
            - action: script.all_notify
              data:
                tit: home_away
                msg: >-
                  {%- set _map = {
                            'on': 'disabled',
                            'off': 'enabled'
                          }
                      -%}
                  is {{ _map[states('input_boolean.away_skip')] }}

input_boolean:
  away_skip:
    name: away skip
    icon: mdi:home-clock-outline
