automation:
  - alias: n0ll_not_home
    trigger:
      - platform: state
        entity_id: device_tracker.n0ll
        to: not_home
        for:
          minutes: 2
    action:
      - service: script.n0ll_not_home

  - alias: root_not_home
    initial_state: off
    trigger:
      - platform: zone
        entity_id: device_tracker.root
        zone: zone.home
        event: leave
    action:
      - service: script.root_not_home

  - alias: home_away
    trigger:
      - platform: numeric_state
        entity_id: proximity.home
        above: 15
    condition:
      - condition: template
        value_template: >-
          {{
            is_state_attr('proximity.home', 'dir_of_travel', 'away_from')
          }}
    action:
      - service: script.home_away

script:
  root_not_home:
    sequence:
      - service: script.finish_lights
      - service: media_player.turn_off
        entity_id:
          - media_player.ht_mt500_501_b34d6a
          - media_player.bedroom_speaker
      - service: script.kodi_turn_off
      - service: automation.turn_on
        entity_id: automation.home_motion_detect
      - service: automation.turn_off
        entity_id:
          - automation.motion_light_extend
          - automation.just_home_auto
          - automation.just_home

  n0ll_not_home:
    sequence:
      - service: script.sound_bar_go_sleep_if
      - service: script.env_xp_light_off
      - service: input_select.select_option
        data:
          entity_id: input_select.hyperion_select_effect
          option: Sparks Color

  home_away_turnoff:
    sequence:
      - service: switch.turn_off
        entity_id:
          - switch.av_switch
          - switch.bed_switch

  home_away:
    sequence:
      - service: notify.gmail
        data:
          message: home away trigger
          title: 'hass'
      - service: automation.turn_off
        entity_id: automation.home_away
      - service: automation.turn_on
        entity_id: automation.home_near
      - service: script.home_away_heating
      - service: script.home_away_turnoff
