sensor:
  - platform: rest
    resource: !secret octobot
    name: octobot
    unique_id: octobot
    value_template: >-
      {{
          (
              (value_json[-1].value|float(0) - value_json[-2].value|float(0)) /
                value_json[-2].value|float(0)
            ) * 100
        }}
    json_attributes_path: "$[-1:]"
    json_attributes:
      - value
      - time
    scan_interval: 600
    unit_of_measurement: '%'
