homeassistant:
  customize:
    script.sound_bar_on:
      icon: mdi:speaker
    script.sound_bar_off:
      icon: mdi:speaker-off
    media_player.ht_mt500_501_b34d6a:
      friendly_name: Sound Bar
    binary_sensor.sound_bar_active:
      friendly_name: Sound bar
    automation.sound_bar_music:
      icon: mdi:speaker-play

template:
  - trigger:
    - trigger: state
      entity_id: media_player.ht_mt500_501_b34d6a
    - trigger: state
      entity_id: media_player.livingtv
    - trigger: state
      entity_id: switch.tv_cec
    - trigger: state
      entity_id: binary_sensor.sound_bar_active
    binary_sensor:
      - name: sound_bar_active
        state: >-
          {{
              is_state('media_player.ht_mt500_501_b34d6a', 'playing') or
                is_state('switch.tv_cec', 'on') or
                is_state('media_player.livingtv', 'playing')
            }}
        icon: >-
          {%- if
                is_state('media_player.ht_mt500_501_b34d6a', 'playing') or
                  is_state('switch.tv_cec', 'on') or
                  is_state('media_player.livingtv', 'playing') or
                  is_state('binary_sensor.sound_bar_active', 'off')
            -%}
            mdi:cast-audio
          {%- else -%}
            mdi:power
          {%- endif -%}
        device_class: sound
        delay_off:
          seconds: 90

automation:
  - alias: sound_bar_music
    id: sound_bar_music
    triggers:
      - trigger: state
        entity_id: media_player.ht_mt500_501_b34d6a
        from: 'off'
        for:
          seconds: 3
        id: to_on
      - trigger: state
        entity_id: input_select.select_sound_bar
        not_from:
          - 'unknown'
          - 'unavailable'
          - 'none'
        id: to_on
      - trigger: event
        event_type: up_down_my
        event_data:
          data: start
        id: start
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id: timer.sound_bar
        id: to_stop
      - trigger: state
        entity_id: binary_sensor.sound_bar_active
        to: 'off'
        id: to_off
      - trigger: state
        entity_id: media_player.ht_mt500_501_b34d6a
        to: 'off'
        for:
          seconds: 5
        id: timer_clear

    mode: restart
    actions:
      - choose:
        - conditions:
          - condition: trigger
            id:
              - to_on
          - condition: state
            entity_id: binary_sensor.kodi_screen_saver
            state: 'on'
          sequence:
            - if:
              - condition: state
                entity_id: input_boolean.enable_sleep
                state: 'on'
              then:
                - action: timer.start
                  entity_id: timer.sound_bar
                  data_template:
                    duration: "00:{{states('input_number.sound_bar_music_timer') | int}}:00"
            - action: media_player.play_media
              data_template:
                entity_id: media_player.ht_mt500_501_b34d6a
                media_content_type: 'audio/mp3'
                media_content_id: >-
                  {% from 'tools.jinja' import name_to_url %}
                  {{ name_to_url('input_select.select_sound_bar') }}

        - conditions:
          - condition: trigger
            id:
              - to_stop
          sequence:
            - action: media_player.turn_off
              entity_id: media_player.ht_mt500_501_b34d6a

        - conditions:
          - condition: trigger
            id:
              - to_off
          sequence:
            - action: script.sound_bar_off

        - conditions:
          - condition: trigger
            id:
              - start
          sequence:
            - action: input_select.set_options
              target:
                entity_id: input_select.select_sound_bar
              data:
                options: >-
                  {% from 'tools.jinja' import radio_names %}
                  {{ radio_names() }}

        - conditions:
          - condition: trigger
            id:
              - timer_clear
          - condition: state
            entity_id: timer.sound_bar
            state:
              - active
              - paused
          sequence:
            - action: timer.cancel
              entity_id: timer.sound_bar

  - alias: sound_bar_input_sleep_on
    id: sound_bar_input_sleep_on
    triggers:
      - trigger: state
        entity_id: input_boolean.enable_sleep
    conditions:
      - condition: state
        entity_id: media_player.ht_mt500_501_b34d6a
        state: 'playing'

    mode: restart
    actions:
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.enable_sleep
            state: 'off'
          sequence:
            - action: timer.cancel
              entity_id: timer.sound_bar

        - conditions:
          - condition: state
            entity_id: input_boolean.enable_sleep
            state: 'on'
          sequence:
            - action: timer.start
              entity_id: timer.sound_bar
              data_template:
                duration: '00:05:00'
            - choose:
              - conditions:
                - condition: or
                  conditions:
                    - condition: state
                      entity_id: input_boolean.enable_sleep
                      state: 'off'
                    - condition: state
                      entity_id: device_tracker.n0ll
                      state: home
                sequence:
                  - action: timer.pause
                    entity_id: timer.sound_bar

input_select:
  select_sound_bar:
    name: sound bar radio
    options:
      - none
    icon: mdi:radio

script:
  sound_bar_off:
    sequence:
      - action: shell_command.sound_bar_off

  sound_bar_on:
    sequence:
      - action: shell_command.sound_bar_on

  radio_on:
    sequence:
      - condition: and
        conditions:
          - condition: state
            entity_id: media_player.ht_mt500_501_b34d6a
            state: 'off'
          - condition: or
            conditions:
            - condition: time
              after: '18:30:00'
              before: '00:05:00'
              weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
            - condition: time
              after: '10:30:00'
              before: '00:35:00'
              weekday:
                - sat
                - sun
      - action: media_player.turn_on
        entity_id: media_player.ht_mt500_501_b34d6a
      - choose:
        - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_boolean.enable_sleep
                state: 'off'
              - condition: state
                entity_id: device_tracker.n0ll
                state: home
          sequence:
            - action: timer.pause
              entity_id: timer.sound_bar
      - wait_template: >-
          {{
              is_state('media_player.ht_mt500_501_b34d6a', 'playing')
            }}
        timeout:
          seconds: 30
      - action: songpal.set_sound_setting
        data:
          entity_id: media_player.soundbar
          name: subwooferLevel
          value: 8
      - action: songpal.set_sound_setting
        data:
          entity_id: media_player.soundbar
          name: voice
          value: type1
      - action: media_player.volume_set
        data:
          entity_id: media_player.ht_mt500_501_b34d6a
          volume_level: 0.16

  sound_bar_go_sleep:
    mode: restart
    sequence:
      - choose:
        - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_boolean.enable_sleep
                state: 'on'
              - condition: time
                after: '13:00:00'
                before: '23:00:00'
          sequence:
            - action: timer.start
              entity_id: timer.sound_bar
              data:
                duration: '00:45:00'

  start_up_sound_bar:
    sequence:
      - if:
        - condition: state
          entity_id: switch.living_tv
          state: 'on'
        then:
            - wait_template: >-
                {{
                    states('media_player.ht_mt500_501_b34d6a') not in ['unknown', 'unavailable']
                  }}
              timeout:
                seconds: 30
              continue_on_timeout: false

            - choose:
              - conditions:
                - condition: state
                  entity_id: media_player.ht_mt500_501_b34d6a
                  state: 'playing'
                sequence:
                  - action: timer.start
                    entity_id: timer.sound_bar

              - conditions:
                - condition: state
                  entity_id: device_tracker.n0ll
                  state: 'home'
                sequence:
                  - action: timer.pause
                    entity_id: timer.sound_bar

        else:
          - action: logbook.log
            data_template:
              name: start_up_sound_bar
              message: 'living_tv is not on'

shell_command:
  sound_bar_off: '/config/cmds/cec_cmd "tx 15:44:6c"'
  sound_bar_on: '/config/cmds/cec_cmd "tx 15:44:6d"'

songpal:
  - name: soundbar
    endpoint: !secret songpal_soundbar

input_boolean:
  enable_sleep:
    name: auto seep
    icon: mdi:sleep

timer:
  sound_bar:
    name: 'sound time'
    icon: mdi:timer-sand
    duration: '00:01:00'

input_number:
  sound_bar_music_timer:
    name: 'music time'
    unit_of_measurement: 'min'
    min: 5
    max: 60
    step: 5
    icon: mdi:av-timer
