homeassistant:
  customize:
    sensor.tomato_disk_free:
      icon: mdi:cloud-sync
    binary_sensor.download_active:
      icon: mdi:download
      hidden: true
    sensor.transmission_status:
      hidden: true

transmission:
  host: !secret trans_host
  port: !secret trans_port
  username: !secret trans_user
  password: !secret trans_pass
  name: trans
  scan_interval: 300

sensor:
  - platform: template
    sensors:
      transmission_state:
        friendly_name: 'Transmission'
        value_template: "{{ states('sensor.trans_status') }}"
        icon_template: >-
          {% if not is_state('sensor.trans_status', 'unknown') -%}
            {%- if is_state('sensor.trans_status', 'Downloading') -%}
              mdi:download
            {%- endif -%}
            {%- if is_state('sensor.trans_status', 'Seeding') -%}
              mdi:upload
            {%- endif -%}
            {%- if is_state('sensor.trans_status', 'Up/Down') -%}
              mdi:pipe
            {%- endif -%}
            {%- if is_state('sensor.trans_status', 'idle') -%}
              mdi:pipe-disconnected
            {%- endif -%}
          {%- else -%}
            mdi:sync-alert
          {%- endif -%}

  - platform: command_line
    #name: tomato disk free rand
    name: tomato disk free
    command: '/config/cmds/tomato_disk_free'
    unit_of_measurement: 'MB'
    scan_interval: 600

binary_sensor:
  - platform: template
    sensors:
      download_active:
        value_template: "{{
                            is_state('sensor.trans_status', 'Downloading') or
                              is_state('sensor.trans_status', 'Up/Down')
                          }}"

automation:
  - alias: transmission_notify
    trigger:
      - platform: event
        event_type: transmission
    action:
      - service: script.all_notify
        data_template:
          tit: '{{ trigger.event.data.file }}'
          msg: 'finished'

  - alias: transmission_idle
    trigger:
      - platform: state
        entity_id: binary_sensor.download_active
        to: 'off'
        from: 'on'
    action:
      - service: script.all_notify
        data:
          tit: 'transmission'
          msg: 'download is idle'
