homeassistant:
  customize:
    light.wash:
      friendly_name: wash
      icon: mdi:door-closed
    automation.wash_light:
      friendly_name: wash
      icon: mdi:lightbulb-auto
    automation.wash_fan:
      friendly_name: wash
      icon: mdi:fan-auto

automation:
  - alias: wash_light
    id: wash_light
    initial_state: false
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.hall_motion
          - binary_sensor.wash_door
        to: 'on'
        id: light_on
      - trigger: state
        entity_id: binary_sensor.hall_occupancy
        to: 'off'
        for:
          seconds: 45
        id: light_off
      - trigger: state
        entity_id: binary_sensor.wash_door
        to: 'off'
        for:
          seconds: 3
        id: light_off
      - trigger: event
        event_type: lights_check
        event_data:
          light: turn_off
        id: light_off

    mode: restart
    actions:
      - choose:
        - conditions:
          - condition: trigger
            id:
              - light_on
          - condition: state
            entity_id: binary_sensor.wash_door
            state: 'on'
          - condition: state
            entity_id: light.wash
            state: 'off'
          sequence:
            - action: light.turn_on
              target:
                entity_id:
                  - light.wash

        - conditions:
          - condition: trigger
            id:
              - light_off
          - condition: state
            entity_id: light.wash
            state: 'on'
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.hall_occupancy
                state: 'off'
              - condition: state
                entity_id: binary_sensor.wash_door
                state: 'off'
          sequence:
            - action: light.turn_off
              target:
                entity_id: light.wash

  - alias: wash_fan
    id: wash_fan
    triggers:
      - trigger: state
        entity_id: binary_sensor.wash_fan
        to: 'on'
        id: dryer_on
      - trigger: state
        entity_id: binary_sensor.wash_fan
        to: 'off'
        id: dryer_off
      - trigger: numeric_state
        entity_id: sensor.bath_hum_change
        above: 10.0
        id: shower_on
      - trigger: state
        entity_id: binary_sensor.showering
        to: 'off'
        id: shower_off
      - trigger: state
        entity_id: input_boolean.fan_wash_time
        to: 'on'
        id: manual_on
      - trigger: state
        entity_id: input_boolean.fan_wash_time
        to: 'on'
        for:
          minutes: >-
            {{
                states('input_number.fan_wash_time') | int(0)
              }}
        id: manual_off
      - trigger: event
        event_type: up_down_my
        event_data:
          data: start
        id: manual_off

    mode: restart
    actions:
      - choose:
        - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - shower_on
                  - dryer_on
                  - manual_on
          - condition: state
            entity_id: switch.wash_fan
            state: 'off'
          sequence:
            - action: switch.turn_on
              data:
                entity_id:
                  - switch.wash_fan

        - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - shower_off
                  - dryer_off
                  - manual_off
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.showering
                    state: 'off'
                  - condition: state
                    entity_id: binary_sensor.wash_fan
                    state: 'off'
          - condition: state
            entity_id: switch.wash_fan
            state: 'on'
          sequence:
            - action: switch.turn_off
              data:
                entity_id:
                  - switch.wash_fan

      - choose:
        - conditions:
          - condition: trigger
            id:
              - shower
              - manual_off
          - condition: state
            entity_id: input_boolean.fan_wash_time
            state: 'on'
          sequence:
            - action: input_boolean.turn_off
              data:
                entity_id:
                  - input_boolean.fan_wash_time

light:
  - platform: group
    name: wash
    entities:
      - light.wash_1

input_boolean:
  fan_wash_time:
     initial: false
     icon: mdi:fan-plus
     name: wash

input_number:
  fan_wash_time:
    name: wash time
    icon: mdi:timer-outline
    min: 2
    max: 20
    step: 2
