input_boolean:
  lumi_double_switch_1:
    initial: off

input_number:
  lumi_double_switch_1_time:
    unit_of_measurement: 'min'
    min: 5
    max: 15
    step: 0.5
    icon: mdi:camera-timer

timer:
  lumi_double_switch_1_timer:
    icon: mdi:timer
    duration: '00:00:30'

script:
  lumi_double_switch_on:
    sequence:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.lumi_double_switch_1
            state: 'off'
          - condition: state
            entity_id: timer.lumi_double_switch_1_timer
            state: 'idle'
      - service: scene.create
        data:
          scene_id: lumi_double_switch
          snapshot_entities:
            - timer.lumi_double_switch_1_timer
            - input_boolean.lumi_double_switch_1
            - light.xp_bar_1
            - light.xp_bar_2
            - light.xp_top_1
            - light.xp_top_2
            - light.hama_living
            - timer.living_light_timer
            - light.ikea_of_sweden_tradfri_bulb_e27_cws_opal_600lm_c66d14fe_level_light_color_on_off
            - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_bd3600fe_level_light_color_on_off
            - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_6aa35efe_level_light_color_on_off
            - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_d7e032fe_level_light_color_on_off
            - timer.bed_light_timer
            - light.hall_light
            - timer.hall_light_timer
            - automation.living_light_trigger
            - automation.bed_light_trigger
            - automation.hall_light_trigger
            - automation.living_light_other_clear
            - automation.bed_light_other_clear
            - automation.hall_light_other_clear
            - automation.motion_light_extend
      - service: timer.start
        data:
          entity_id: timer.lumi_double_switch_1_timer
        data_template:
          duration: >-
            {{ time_t | string }}
      - service: input_boolean.turn_on
        entity_id: input_boolean.lumi_double_switch_1
      - service: timer.pause
        data:
          entity_id:
            - timer.bed_light_timer
            - timer.hall_light_timer
            - timer.living_light_timer
      - service: automation.turn_off
        data:
          entity_id:
            - automation.living_light_trigger
            - automation.bed_light_trigger
            - automation.hall_light_trigger
            - automation.living_light_other_clear
            - automation.bed_light_other_clear
            - automation.hall_light_other_clear
            - automation.motion_light_extend
      - service: light.turn_on
        data:
          entity_id:
            - light.xp_bar_1
            - light.xp_bar_2
            - light.xp_top_1
            - light.xp_top_2
          color_temp: 327
          brightness_pct: 75
      - service: light.turn_on
        data:
          entity_id: light.hama_living
          white_value: 232
      # transition not work if current and
      # target brightness are diffrent
      - service: light.turn_on
        data:
          entity_id: light.ikea_of_sweden_tradfri_bulb_e27_cws_opal_600lm_c66d14fe_level_light_color_on_off
          rgb_color: [255, 255, 255]
          brightness_pct: 1
      - service: light.turn_on
        data:
          entity_id: light.hall_light
          brightness_pct: 1
          kelvin: 5000
      - service: light.turn_on
        data:
          entity_id:
            - light.hall_light
            - light.ikea_of_sweden_tradfri_bulb_e27_cws_opal_600lm_c66d14fe_level_light_color_on_off
          brightness_pct: 75
          transition: 10

  restore_hama_random_effect_workaround:
    sequence:
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.light_h
            state: 'on'
      - service: automation.trigger
        data:
          entity_id: automation.light_h_on

  lumi_double_switch_off:
    sequence:
      - service: scene.turn_on
        data:
          entity_id: scene.lumi_double_switch
      - service: script.restore_hama_random_effect_workaround

automation:
  - alias: lumi_switch_double_trigger_1
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: '00:15:8d:00:02:b0:7a:42'
          command: 'shake'
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: '00:15:8d:00:02:a7:21:9f'
          command: 'shake'
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.lumi_double_switch_1_timer
    action:
      - service_template: >
          {%- if is_state('input_boolean.lumi_double_switch_1', 'on') -%}
            script.lumi_double_switch_off
          {%- else -%}
            script.lumi_double_switch_on
          {%- endif -%}
        data_template:
          time_t: >-
            {{ (states('input_number.lumi_double_switch_1_time') | float * 60.0) | int }}
