#!/bin/bash
source $HOME/.homeassistant/set_env

SSHPASS=$PASS sshpass -e \
ssh $USERNAME@$HOST \
"echo $1  > /sys/devices/virtual/amhdmitx/amhdmitx0/cec"

# echo "e" > /sys/devices/virtual/amhdmitx/amhdmitx0/cec - on
# echo "d" > /sys/devices/virtual/amhdmitx/amhdmitx0/cec - off
# echo "14" > /sys/devices/virtual/amhdmitx/amhdmitx0/cec - select
# echo "14 5" > /sys/devices/virtual/amhdmitx/amhdmitx0/cec - select
# echo "1b 05 6c" > /sys/devices/virtual/amhdmitx/amhdmitx0/cec - off
# echo "1b 05 6d" > /sys/devices/virtual/amhdmitx/amhdmitx0/cec

# echo "1b 5 41" > /sys/devices/virtual/amhdmitx/amhdmitx0/cec up
# echo "1b 5 42" > /sys/devices/virtual/amhdmitx/amhdmitx0/cec
# echo "1b 5 43" > /sys/devices/virtual/amhdmitx/amhdmitx0/cec
