#!/bin/bash
source $HOME/.homeassistant/set_env

SSHPASS=$PASS sshpass -e \
ssh $USERNAME@$HOST \
'kodi-send --action="ActivateScreensaver" &&\
  sleep 1 && \
  /storage/.config/system.d/ha_start.sh'
