#!/bin/bash
source $HOME/.homeassistant/set_env

curl --user $HTTPUSER:$HTTPPASS -s \
--data-binary '{"jsonrpc": "2.0", "method": "Addons.ExecuteAddon", "params": {"addonid": "plugin.program.braviacontrol", "params": ["VolumeDown"]}, "id": 1}' \
-H 'content-type: application/json;' \
http://minix:80/jsonrpc
